FROM ubuntu:22.04

COPY . .
RUN apt-get update && \
    apt-get install -y sudo
RUN sudo apt-get install curl -y
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sudo sh get-docker.sh

EXPOSE 3002

CMD ["sudo", "docker", "compose", "up", "-d", "backend", "client", "clickhouse", "postgres"]
