FROM ubuntu:22.04

COPY . .
RUN apt update
RUN apt install sudo -y
RUN sudo apt-get install curl -y
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sudo sh get-docker.sh

CMD ["sudo", "docker", "compose". "up", "-d", "backend", "client", "clickhouse", "postgres"]
